code_mapping = {
    1: 'Oberschicht',
    2: 'Bildungsbürgertum',
    3: 'HandwerkEtc',
    4: 'FacharbeiterEtc',
    5: 'Unterschicht',
    0: None
}


occupations_mapping = {
    'Kaufmann': 2,
    'Pastor': 2,
    'Gutsbesitzer': 1,
    'Prediger': 2,
    'Pfarrer': 2,
    'Amtmann': 1,
    'Wittwe': 0,
    'Apotheker': 2,
    'Hofrath': 1,
    'Oeconom': 3,
    'Schullehrer': 2,
    'Superintendent': 2,
    'Kaufm.': 2,
    'Bürgermeister': 1,
    'Advocat': 2,
    'Dr. med.': 2,
    'Privatmann': 2,
    'Professor': 2,
    'Regierungsrath': 1,
    'Gastwirth': 3,
    'Oekonom': 3,
    'Particulier': 2,
    'Justizrath': 1,
    'Senator': 1,
    'Arzt': 2,
    'Handelsmann': 3,
    'Landrath': 1,
    'Major': 1,
    'Oberamtmann': 1,
    'Landmann': 3,
    'Cantor': 2,
    'Hauptmann': 1,
    'Rath': 1,
    'Rentmeister': 1,
    'Chirurgus': 2,
    'Oberförster': 1,
    'Postmeister': 1,
    'Kammerherr': 1,
    'Banquier': 2,
    'Dr. jur.': 2,
    'Lehrer': 2,
    'Bürger': 0,
    'Notar': 2,
    'Bäcker': 3,
    'Geh. Rath': 1,
    'Rittergutsbesitzer': 1,
    'Gutsbes.': 1,
    'Amtm.': 1,
    'Doctor': 2,
    'Weinhändler': 2,
    'Consistorialrath': 1,
    'Medicinalrath': 1,
    'Schneidermeister': 3,
    'Predig.': 2,
    'Hofgerichtsrath': 1,
    'Müller': 3,
    'Kammerrath': 1,
    'Staatsrath': 1,
    'Wundarzt': 2,
    'Obristlieutenant': 1,
    'Landwirth': 3,
    'Forstmeister': 1,
    'Rentier': 2,
    'Rittmeister': 1,
    'Förster': 3,
    'Wirth': 3,
    'Organist': 2,
    'Schuhmacher': 3,
    'Oberforstmeister': 1,
    'Kaufmannswittwe': 2,
    'Friedensrichter': 1,
    'Kirchenrath': 1,
    'Hofmedicus': 2,
    'Assessor': 1,
    'Oberst': 1,
    'Registrator': 2,
    'Bäckermeister': 3,
    'Advokat': 2,
    'Majorenn': 0,
    'Drost': 1,
    'Procurator': 2,
    'Hofkammerrath': 1,
    'Buchhändler': 2,
    'Dr.': 2,
    'Steuereinnehmer': 1,
    'Amtsvoigt': 1,
    'Oecon.': 3,
    'Schneider': 3,
    'Superint.': 2,
    'Chirurg': 2,
    '† Kaufmann': 2,
    'Postverwalter': 1,
    'Amtsassessor': 1,
    'Amtsrath': 1,
    'Pastorin': 2,
    'Oberappellationsrath': 1,
    'Pächter': 3,
    'Geh. Hofrath': 1,
    'Landrichter': 1,
    'Secretair': 2,
    'Rector': 2,
    'Bauer': 3,
    'verw. Pastorin': 2,
    'Fabrikant': 2,
    'Geheimerath': 1,
    'Präsident': 1,
    'Ackermann': 3,
    'Oberhauptmann': 1,
    'Reitender Förster': 3,
    'Probst': 2,
    'Cammerrath': 1,
    'Justizamtmann': 1,
    'Mutter': 0,
    'Rentamtmann': 1,
    'Färber': 3,
    'Oberbürgermeister': 1,
    'Stadtrath': 1,
    'Generalmajor': 1,
    'Bierbrauer': 3,
    'Thierarzt': 2,
    'Einnehmer': 1,
    'Kriegsrath': 1,
    'Legationsrath': 1,
    'Posthalter': 3,
    'Rentner': 2,
    'Landdrost': 1,
    'Ackersmann': 3,
    'Stadtrichter': 1,
    'Kreiseinnehmer': 1,
    'Minister': 1,
    'Geh. Justizrath': 1,
    'Obrist': 1,
    'Geh. Regierungsrath': 1,
    'Richter': 1,
    'Notarius': 2,
    'Landchirurgus': 2,
    'Buchbinder': 3,
    'Uhrmacher': 3,
    'Notär': 2,
    'Commissair': 1,
    'Edelmann': 1,
    'Capitain': 1,
    'Gastgeber': 3,
    'Hausvoigt': 3,
    'Doctor med.': 2,
    'Witwe': 0,
    'Amtsverwalter': 1,
    'Lieutenant': 1,
    'Director': 1,
    'Prof.': 2,
    'Brauer': 3,
    'Kreisrath': 1,
    'Generalsuperintendent': 2,
    'Dr. Med.': 2,
    'Rechnungsrath': 1,
    'Regierungs-Rath': 1,
    'Guthsbesitzer': 1,
    'Graf': 1,
    'Rathsherr': 1,
    'Oberamtm.': 1,
    'Amtsrevisor': 1,
    'Oekon.': 3,
    'Decan': 2,
    'Gastwirt': 3,
    'Goldarbeiter': 3,
    'Stadtschreiber': 2,
    'Geh. Finanzrath': 1,
    'Predigerwittwe': 2,
    'Past.': 2,
    'Beamter': 1,
    'Gerichtsverwalter': 1,
    'Cämmerer': 1,
    'Metzger': 3,
    'Oberlandesgerichtsrath': 1,
    'Vater †': 0,
    'Verwalter': 3,
    'Landm.': 3,
    'Medizinalrath': 1,
    'Stadtpfarrer': 2,
    'Oberstlieutenant': 1,
    'General': 1,
    'Hofmarschall': 1,
    'Obercommissair': 1,
    'Maire': 1,
    'Tischler': 3,
    'Kanzleirath': 1,
    'Amtsvogt': 1,
    'Appellationsrath': 1,
    'Hofprediger': 2,
    'Geheimerrath': 1,
    'Privatm.': 2,
    'Obereinnehmer': 1,
    'Oberlehrer': 2,
    'Partikulier': 2,
    'Syndicus': 2,
    'Dekan': 2,
    'Rendant': 1,
    'Domainenrath': 1,
    '† Pfarrer': 2,
    'Commerzienrath': 1,
    'Steuerrath': 1,
    'Amtshauptmann': 1,
    'Oberwundarzt': 2,
    'Ministerialrath': 1,
    'Vo. Mutter': 0,
    'Obermedicinalrath': 1,
    'Lederhändler': 3,
    'Kaufmanns-Wittwe': 2,
    'Kaufmann †': 2,
    'Buchdrucker': 3,
    'Kauffmann': 2,
    'Justizcommissair': 1,
    'Oberregierungsrath': 1,
    'Bergrath': 1,
    'Jnspector': 2,
    'Metropolitan': 2,
    'Doctor juris': 2,
    'Commissionsrath': 1,
    'Finanzrath': 1,
    'Justiz-Rath': 1,
    'Vogt': 3,
    'Revisor': 2,
    'Seifensieder': 3,
    'Forstrath': 1,
    'Kammerdiener': 4,
    'Hofräthin': 1,
    'Amtsschreiber': 2,
    'Cammerherr': 1,
    'Geistlicher': 2,
    'Postdirector': 1,
    'Oberhofgerichtsrath': 1,
    'Geheimer Rath': 1,
    'Stallmeister': 3,
    'Oberforstrath': 1,
    'Canzleyrath': 1,
    'Domainenpächter': 3,
    'Administrator': 2,
    'Oberjägermeister': 1,
    'Oberappellationsgerichtsrath': 1,
    'todt': 0,
    'Stadtsyndicus': 2,
    'Schuhmachermeister': 3,
    'Holzhändler': 3,
    'Dr. juris': 2,
    'Privatier': 2,
    'Zimmermeister': 3,
    'Conductor': 3,
    'Eigenthümer': 3,
    'Kantor': 2,
    'Hauptm.': 1,
    'Gerichtsschreiber': 2,
    'Major a. D.': 1,
    'Kammerdirector': 1,
    'Kämmerer': 1,
    'Canzlist': 3,
    'Oberconsistorialrath': 1,
    'Justizcommissar': 1,
    'Etatsrath': 1,
    'Baumeister': 2,
    '† Apotheker': 2,
    'Baron': 1,
    'Schumacher': 3,
    'Lohgerber': 3,
    'Justiz-Commissair': 1,
    'Gastw.': 3,
    'Factor': 3,
    'Revierförster': 3,
    'Oberfactor': 2,
    'Conrector': 2,
    'Auctionsverwalter': 2,
    'Obergerichtsrath': 1,
    'Hofapotheker': 2,
    'Inspector': 2,
    'Rektor': 2,
    'Steuer-Einnehmer': 1,
    'Obervogt': 1,
    'Obervoigt': 1,
    'Gerichtsbote': 4,
    'Oberfinanzrath': 1,
    'Gerichtshalter': 1,
    'Amtschreiber': 2,
    'Mauermeister': 3,
    'Hauptmann a. D.': 1,
    'Kammerdirektor': 1,
    'Makler': 3,
    'Tischlermeister': 3,
    'Staatsminister': 1,
    'Geheimrath': 1,
    'Gerber': 3,
    'Amtmannin': 1,
    'Cammerconsulent': 2,
    'Landbaumeister': 2,
    'Küster': 3,
    'Präpositus': 2,
    'Justitzrath': 1,
    'Lederfabrikant': 2,
    'Amtschirurg': 2,
    'Physicus': 2,
    'Stadtdirektor': 1,
    'Regierungsdirector': 1,
    'Cassirer': 2,
    'Landrentmeister': 1,
    'Maler': 3,
    'verw. Doctorin': 2,
    'Geheimer Justizrath': 1,
    'Landphysicus': 2,
    'Oberpostmeister': 1,
    'Kaufman': 2,
    'Regierungsdirektor': 1,
    'Landsyndicus': 2,
    'verw. Kaufmannin': 2,
    'Kommerzienrath': 1,
    'Spediteur': 3,
    'Stadt-Chirurgus': 2,
    'Physikus': 2,
    'Sattler': 3,
    'Dr. phil.': 2,
    'Canzleirath': 1,
    'Justizräthin': 1,
    'propriétaire': 1,
    'Ackerm.': 3,
    'Sattlermeister': 3,
    'Oberbergrath': 1,
    'Regierungspräsident': 1,
    'General-Major': 1,
    'Papierfabrikant': 2,
    'Fürst': 1,
    'Kreis-Einnehmer': 1,
    'Maurermeister': 3,
    'Merchant': 2,
    'Gärtner': 3,
    'Particular': 2,
    'Rothgerber': 3,
    'Geh. Staatsrath': 1,
    'Prediger-Wittwe': 2,
    'Metzgermeister': 3,
    'Canzley-Secretair': 2,
    'Forstinspector': 2,
    'Hofgärtner': 3,
    'Amtsphysikus': 2,
    'Musiklehrer': 2,
    'Stadtschultheisz': 1,
    'Postmeist.': 1,
    'Gutspächter': 3,
    'Rentenier': 2,
    'Doctor Medicinae': 2,
    'Commissions-Rath': 1,
    'Rittmeister a. D.': 1,
    'Steuerdirector': 1,
    'Landchirurg': 2,
    'Buchhalter': 3,
    'Pastor prim.': 2,
    'Witwe K.': 0,
    'prakt. Arzt': 2,
    'Gutsbesitzerin': 1,
    'Becker': 3,
    'Land- u. Stadtgerichtsrath': 1,
    'Geh. Kammerrath': 1,
    'Camerarius': 1,
    'Justizcommissarius': 1,
    'Güterbesitzer': 1,
    'Regierungs-Secretair': 2,
    'Oberstallmeister': 1,
    'Ökonom': 3,
    'Privat': 2,
    'verw. Amtmannin': 1,
    'Obergerichtsadvokat': 2,
    'Wittib': 0,
    'Geh. Cabinetsrath': 1,
    'Majorin': 1,
    'Hofrat': 1,
    'Seiler': 3,
    'Kreisamtmann': 1,
    'Webermeister': 3,
    'Regierungsrat': 1,
    'Direktor': 1,
    'Stadtchirurgus': 2,
    'Burgemeister': 1,
    'Oberamtsrichter': 1,
    'Zollverwalter': 1,
    'Schulrath': 1,
    'Landgerichtsrath': 1,
    'Privatlehrer': 2,
    'Conditor': 3,
    'Juwelier': 3,
    'Opfermann': 4,
    'Generalsuperint.': 2,
    'Landjägermeister': 1,
    'Geh. Cammerrath': 1,
    'Geh. Legationsrath': 1,
    'Oberprediger': 2,
    'Postdirektor': 1,
    'Werkmeister': 3,
    'Kreisdirektor': 1,
    'Handelsman': 3,
    'Schiffer': 3,
    'Doctor Med.': 2,
    'Canzley-Procurator': 2,
    'Hutmacher': 3,
    'Amtsrichter': 1,
    'Oberpräsident': 1,
    'Geh. Oberfinanzrath': 1,
    'Landrat': 1,
    'Gutsbesitz.': 1,
    'Hofrath u. Professor': 2,
    'Kanzleyrath': 1,
    'Schreinermeister': 3,
    'Canzleydirector': 1,
    'Essigbrauer': 3,
    'Bader': 3,
    'Justizbeamter': 1,
    'Doctor medicinae': 2,
    'Gerichtsdirector': 1,
    'Hutfabrikant': 2,
    '† Professor': 2,
    'Tribunalrichter': 1,
    'Archivrath': 1,
    'Ober-Commissair': 1,
    'Schreiner': 3,
    'Witwe d. Dr. M.': 2,
    'Kameralverwalter': 1,
    'Gerichtsrath': 1,
    'Schönfärber': 3,
    'Sprachlehrer': 2,
    'Advocat und Notar': 2,
    'Kaufmann (deceased)': 2,
    'Räthin': 1,
    'Glaser': 3,
    'Kleidermacher': 3,
    'Silberarbeiter': 3,
    'Oberbaurath': 1,
    'Geometer': 2,
    'Krämer': 3,
    'Secretär': 2,
    'Justizrat': 1,
    'Schumachermeister': 3,
    'merchant': 2,
    'Fleischer': 3,
    'Forstinspektor': 2,
    'Konsistorialrath': 1,
    'Regimentsarzt': 2,
    'Actuar': 2,
    'Hofadvocat': 2,
    'particulier': 2,
    'Geh. Oberregierungsrath': 1,
    'Kreis-Amtmann': 1,
    'Abt': 2,
    'Weber': 4,
    'Oberzollinspektor': 1,
    'Obersteuerrath': 1,
    'Apothek.': 2,
    'Obristlieut.': 1,
    'Steuerrevisor': 2,
    'Geheime Rath': 1,
    'Schultheiss': 1,
    'Schmidt': 3,
    'Amtsrentmeister': 1,
    'Postspediteur': 3,
    'Consistorialräthin': 1,
    'Archivar': 2,
    'Wittwe des Kaufmanns': 2,
    'Ober-Appellations-Rath': 1,
    'Kreisrevisor': 2,
    'Praetor': 1,
    'Steuerdirektor': 1,
    'Capitaine': 1,
    'Auditeur': 2,
    'Witwe d. Kaufmanns Sch.': 2,
    'Amts-Assessor': 1,
    'Amtsphysicus': 2,
    'Bauinspector': 2,
    'Subrector': 2,
    'Baurath': 1,
    'Geh. Kriegsrath': 1,
    'Cammer-Commissair': 1,
    'Kammerassessor': 1,
    'Oberrechnungsrath': 1,
    'Senatorin': 1,
    '† Amtmann': 1,
    'Kreisrichter': 1,
    'Consistorial-Secretair': 2,
    'Gesandter': 1,
    '† Lehrer': 2,
    'Friseur': 3,
    'Doctorin': 2,
    'Tuchfabrikant': 2,
    'Diaconus': 2,
    'Gouverneur': 1,
    'Pferdehändler': 3,
    'Vo. Kaufmann': 2,
    'Fabricant': 2,
    'Postsecretair': 2,
    'Chirurg.': 2,
    'Witwe B.': 0,
    'Mühlenmeister': 3,
    'Oberappellations-Rath': 1,
    'Hofrichter': 1,
    'Brauereibesitzer': 2,
    'Rentbeamter': 1,
    'Stadtsecretair': 2,
    'Canton-Maire': 1,
    'Bibliotheks-Pedell': 4,
    'Oberhauptm.': 1,
    'Amtmännin': 1,
    'Pensionair': 2,
    'Fabrikbesitzer': 2,
    'Branntweinbrenner': 3,
    'Inspektor': 2,
    'Pfarrer †': 2,
    'Archidiaconus': 2,
    'Gentleman': 1,
    'Witwe d. Pastors R.': 2,
    'Geheimer Regierungsrath': 1,
    'Regierungsadvocat': 2,
    'Mühlenpächter': 3,
    'Gutsbesitzerinn': 1,
    'Stadt-Syndicus': 2,
    'Witwe H.': 0,
    'Braumeister': 3,
    'Kanzlist': 3,
    'Kreisphysicus': 2,
    'Advokat-Anwalt': 2,
    'Oberpfarrer': 2,
    'Gutsbesitzer †': 1,
    'Kammerpräsident': 1,
    'Négociant': 2,
    'privatisirend': 2,
    'Geh. Oberbaurath': 1,
    'eigner Herr': 2,
    'Oberschulrath': 1,
    'Generalin': 1,
    'Stadtphysicus': 2,
    'Senior Ministerii': 2,
    'Witwe W.': 0,
    'Steuerinspektor': 2,
    'Regierungsräthin': 1,
    'Witwe d. Dr. R.': 2,
    'Bergmeister': 1,
    'Münzmeister': 2,
    'Commissionair': 3,
    'Med. Dr.': 2,
    'Generallieutenant': 1,
    'Landbauer': 3,
    'Kunstgärtner': 3,
    'Postrath': 1,
    'Oberschultheiss': 1,
    'Gymnasialdirektor': 2,
    'Rechnungskammerrath': 1,
    'Bezirksförster': 3,
    'Eisenhändler': 3,
    'Schulmeister': 2,
    'Canzley-Director': 1,
    'verw. Lieutenantin': 1,
    'Nobilis': 1,
    'Dr. med. et chir.': 2,
    'Kantonsarzt': 2,
    'Bergmann': 4,
    'Doctor der Medicin': 2,
    'Canzleidirector': 1,
    'Hauptmannin': 1,
    'Müllermeister': 3,
    'General-Lieutenant': 1,
    'Cammerarius': 1,
    'Knopfmacher': 3,
    'Hofmeister': 2,
    'verwittwete Pastorin': 2,
    'Schmiedemeister': 3,
    'Glasermeister': 3,
    'Zollinspector': 2,
    'Regierungs-Director': 1,
    'Landschaftsdirector': 1,
    'verw. Gutsbesitzerin': 1,
    'Land- und Stadtrichter': 1,
    'Witwe d. Pastors H.': 2,
    'Kammer-Rath': 1,
    'Consistorial-Rath': 1,
    'Reit. Förster': 3,
    'Bezirksrichter': 1,
    'Auctionator': 3,
    'Landesdirektor': 1,
    'Medicinalrath Dr.': 1,
    'Obertribunalrath': 1,
    'Kammerräthin': 1,
    'Amts-Chirurgus': 2,
    'Oberrentmeister': 1,
    'Oeconome': 3,
    'Pedell': 4,
    'Tuchmacher': 3,
    'Actuarius': 2,
    'Hoffrath': 1,
    'Praesident': 1,
    'Kaufleute': 2,
    'Leineweber': 4,
    'Burgermeister': 1,
    'Obristlieutnant': 1,
    'Regierungssecretair': 2,
    'Landschreiber': 2,
    'Briefträger': 4,
    'Friedens-Richter': 1,
    'Oberhütteninspector': 1,
    'Zahlmeister': 2,
    'Bürgermeisterin': 1,
    'Geheimer Hofrath': 1,
    'Goldschmidt': 3,
    'Pred.': 2,
    'Apothecker': 2,
    'Vormund': 0,
    'Oberrichter': 1,
    'Canzellist': 3,
    'Weinwirth': 3,
    '† Bürgermeister': 1,
    'Witwe d. Kaufmanns F.': 2,
    'Tierarzt': 2,
    'verw. Professorin': 2,
    'Wagner': 3,
    '† Dr. med.': 2,
    'Doctor jur.': 2,
    'Voigt': 3,
    'Fähndrich': 1,
    'Gerichtschreiber': 2,
    'Cantor u. Schullehrer': 2,
    'Thorschreiber': 3,
    'Notaire': 2,
    'Schuster': 3,
    'Justiz-Commissarius': 1,
    '† Hauptmann': 1,
    '† Müller': 3,
    'Bürgerm.': 1,
    'Oberpostdirector': 1,
    'Rath und Amtmann': 1,
    'Witwe R.': 0,
    'Kammerjunker': 1,
    'Kanzler': 1,
    'Leibmedicus': 2,
    'Witwe M.': 0,
    'Haushofmeister': 2,
    'Privatman': 2,
    'Generalstabsarzt': 2,
    'Calculator': 3,
    'Ritterguts- besitzer': 1,
    'Hüttenmeister': 3,
    'Kirchspielvogt': 1,
    'Hofjägermeister': 1,
    'Advocat-Anwalt': 2,
    'Kreisphysikus': 2,
    'Landoberschultheisz': 1,
    'Kaufmann W.': 2,
    '† Landwirth': 3,
    'Oberverwalter': 2,
    'Wittwe des Dr. med.': 2,
    '† Justizrath': 1,
    'Stadtdirector': 1,
    'Negotiant': 2,
    'k. preusz. Landrath': 1,
    'Witwe d. Pastors G.': 2,
    'Kornhändler': 3,
    'verw.': 0,
    'Koch': 4,
    'Oberappellationsrat': 1,
    'Oberrevisor': 1,
    'verw. Majorin': 1,
    'Cammersecretair': 2,
    'Stiftsprediger': 2,
    'Oberamtsarzt': 2,
    '† Gutsbesitzer': 1,
    'Witwe d. Pastors B.': 2,
    'Witwe d. Dr. G.': 2,
    'Rechtsconsulent': 2,
    'Rabbiner': 2,
    'Dechant': 2,
    'Geh. Hofrath u. Professor': 2,
    '† Oberamtmann': 1,
    'major.': 0,
    'Fuhrmann': 4,
    'verw. Bürgermeisterin': 1,
    'Hofrath u. Bürgermeister': 1,
    'Regiments-Chirurgus': 2,
    'General-Superintendent': 2,
    'Öconom': 3,
    'Amtskeller': 1,
    'Kiefer': 3,
    'Oberstlieut.': 1,
    'Vicarius': 2,
    'Consistorial-Assessor': 1,
    'Vicepraesident': 1,
    'Oberlandes- gerichtsrath': 1,
    'Oberlandesgerichts-Rath': 1,
    'Rat': 1,
    'Justizcommissionsrath': 1,
    'Witwe Sch.': 0,
    'Geldwechsler': 3,
    'Regierungs-director': 1,
    'verw. Amtsassessorin': 1,
    'Zinngiesser': 3,
    'Zollinspektor': 2,
    'Oberdeichgräfe': 1,
    '† Arzt': 2,
    'Gerichtspräsident': 1,
    'Mühlenbesitzer': 3,
    'Musicus': 3,
    'majorenn': 0,
    'Färbermeister': 3,
    'Commandant': 1,
    'Kreis-Controleur': 1,
    'Staatsanwalt': 1,
    'Dr. jur. Breithaupt': 2,
    'Stadtwundarzt': 2,
    'k. preusz. Major': 1,
    'Kriegs-Commissair': 1,
    'Med. Doctor': 2,
    'Schmied': 3,
    'Hausvogt': 3,
    'Partikülier': 2,
    'Hofmedikus': 2,
    'Pfarrerswittwe': 2,
    'reitender Förster': 3,
    'Kanzleidirektor': 1,
    'Musikdirektor': 2,
    'Hofchirurgus': 2,
    'Nachrichter': 4,
    'Hypothekenbewahrer': 1,
    'Artzt': 2,
    'Hauptpastor': 2,
    'Renovator': 3,
    'Jnstrumentenmacher': 3,
    'Collegienrath': 1,
    'Medicinal-Rath': 1,
    'Wegbaumeister': 2,
    'Bergchirurgus': 2,
    'Witwe d. Kaufmanns M.': 2,
    'Witwe d. Kaufmanns W.': 2,
    'Freyherr': 1,
    'Hofrath Dr.': 1,
    'Schlossermeister': 3,
    'Amtshauptm.': 1,
    'Superintendentin': 2,
    'Antiquar': 3,
    'Chir.': 2,
    '† Rentier': 2,
    'Reg.-Rath': 1,
    '† Regierungsrath': 1,
    'Stadt-Secretär': 2,
    'ref. Prediger': 2,
    'Regierungssekretär': 2,
    'Doktor': 2,
    'Criminalrath': 1,
    '† Rentner': 2,
    'Assessorin': 1,
    'Berginspector': 2,
    'Regierungs-Direktor': 1,
    'Geh. Canzley-Rath': 1,
    'Vorsänger': 3,
    'Mechanicus': 3,
    'Klempner': 3,
    'Mühlenschreiber': 3,
    'Gutsbesitzer auf': 1,
    'Mutter Wittwe': 0,
    'Geheimeräthin': 1,
    'k. preusz. Kammerherr': 1,
    'Rathmann': 1,
    'juge de paix': 1,
    'weil. Prediger': 2,
    'Oberinspector': 1,
    '† Rittergutsbesitzer': 1,
    'Schichtmeister': 3,
    'Rath u. Amtmann': 1,
    '† Hofrath': 1,
    'Markscheider': 2,
    'Gastwirthin': 3,
    'Hauptman': 1,
    'ist sein eigner Herr': 2,
    'Wittwe des Cantors': 2,
    'Kaufm': 2,
    'verw. Einnehmerin': 1,
    'Hofmaler': 2,
    'verwittwete Doctorin': 2,
    'Erbpächter': 3,
    'Steuerinspector': 2,
    'Stadt-Wundarzt': 2,
    'Landbesitzer': 1,
    'Oberzollinspector': 1,
    'Zimmermann': 3,
    'Oberförst.': 1,
    'Assistenz-Rath': 1,
    'Praepositus': 2,
    'Deichvoigt': 3,
    'Salzinspector': 2,
    'Essigfabrikant': 2,
    'Pastorinn': 2,
    'Professorin': 2,
    'Königl. Dänischer Kammerherr': 1,
    'Architect': 2,
    'Landökonom': 3,
    'Kriegesrath': 1,
    'Geheimer Finanzrath': 1,
    'pens. Amtmann': 1,
    'Oberforstmeist.': 1,
    'Rechnungsführer': 3,
    'Appellations-gerichtsrath': 1,
    'Hofgerichtsadvokat': 2,
    'Ober-Amtmann': 1,
    'Assistenzrath': 1,
    'Wittwe d. Kaufmanns': 2,
    '† Gastwirth': 3,
    'Pfarrerin': 2,
    'Forstsecretair': 2,
    'Mundkoch': 4,
    'Landbereiter': 3,
    'Hütteninspector': 2,
    'Schatzeinnehmer': 1,
    'Sensal': 3,
    'Justizcommiss.': 1,
    'Wittwe Gutsbesitzerin': 1,
    'Münzdirector': 1,
    'Justiz-Commissar': 1,
    'Pastorin (widow)': 2,
    'Geheime Cabinetsrath': 1,
    'Rentnerin': 2,
    'Scharfrichter': 4,
    'Commerzrath': 1,
    'Hoffactor': 2,
    'Hofrath Dr. med.': 1,
    'Landmarschall': 1,
    'Regierungs- u. Consistorialrath': 1,
    'Gutsbesizer': 1,
    'Bundestagsgesandter': 1,
    'Colonel': 1,
    'Landessecretair': 2,
    'Maurer': 3,
    'Weisgerber': 3,
    'Witwe L.': 0,
    'Justiz-commissair': 1,
    'Kürschner': 3,
    'Landgerichts-rath': 1,
    'Expeditor': 3,
    'Ober-Postmeister': 1,
    'major': 0,
    'Geh. Referendär': 1,
    'Justizcomm.': 1,
    'Secretaire': 2,
    'Musikus': 3,
    'Prorector': 2,
    'Geheime Kriegsrath': 1,
    'Oberst a. D.': 1,
    '† Handelsmann': 3,
    'Witwe d. Hauptmanns D.': 1,
    'Unterpedell': 4,
    'Konsistorialrat': 1,
    'Elementarlehrer': 2,
    'Amtssekretär': 2,
    'Gold- und Silberarbeiter': 3,
    'Landgerichtsassessor': 1,
    '† Landrath': 1,
    'Clergyman': 2,
    'Major u. Ritter': 1,
    'Lieutnant': 1,
    'Controlleur': 2,
    'Hausmann': 4,
    'verw. Hauptmannin': 1,
    'Domänenverwalter': 2,
    'Drechsler': 3,
    'Doctor der Rechte': 2,
    'Justizdirector': 1,
    'Amtscommissair': 1,
    'Geheimräthin': 1,
    'Domainenrentmeister': 1,
    'Hüttenbesitzer': 2,
    'Bäcker u. Wirth': 3,
    'Gerichtsvoigt': 3,
    'Praeceptor': 2,
    'Steuer-Direktor': 1,
    'Schultheis': 1,
    'Witwe d. Kaufmanns K.': 2,
    'Gerichtsrat': 1,
    '† Bierbrauer': 3,
    'Wittwe des Advocaten': 2,
    'Kommissionsrath': 1,
    'Kreissecretair': 2,
    'Landcommissair': 1,
    'Schatzrath': 1,
    'Bergsyndicus': 2,
    'Senior': 2,
    'Majeur': 1,
    'Witwe d. Kaufmanns H.': 2,
    'Justiz-Amtmann': 1,
    'Jurist': 2,
    'Witwe d. Pastors K.': 2,
    'Tribunal-Richter': 1,
    'Geschäftsmann': 3,
    'Prokurator': 2,
    'Küchenmeister': 3,
    'Arbeitsmann': 5,
    'Schlossverwalter': 2,
    'Cammer-Rath': 1,
    'Cammerherrin': 1,
    'Schulze': 1,
    'verw. Hofräthin': 1,
    'Hofsattler': 3,
    'Landräthin': 1,
    'Instrumentenmacher': 3,
    'Generallieut.': 1,
    'Esq.': 1,
    'Canzlei-Secretair': 2,
    'Cammerdirector': 1,
    'Witwe d. Pastors St.': 2,
    'Staatsmann': 1,
    'Gemeindeschreiber': 2,
    'Gasthalter': 3,
    'Mehlhändler': 3,
    'Chyrurg': 2,
    'Steuerempfänger': 1,
    'Obergerichtsdirector': 1,
    'Hofgerichtsdirektor': 1,
    'Obergerichtsadvocat': 2,
    'Bezirksamtmann': 1,
    'Gartenmeister': 3,
    '† Partikulier': 2,
    'Lieut.': 1,
    'Professor am Gymnasium': 2,
    'Archidiakonus': 2,
    'Domainenverwalter': 2,
    'Oberamtman': 1,
    'Notair': 2,
    'Stadtbaumeister': 2,
    'Schlosser': 3,
    'Landchirurg.': 2,
    'Obersteuerrat': 1,
    'Grundherr': 1,
    'Vo. Kreisrath v. Micheroux': 1,
    'Oberhauptmannin': 1,
    'Zuckerfabrikant': 2,
    'Schaffner': 4,
    'Rechtsgelehrter': 2,
    'Rathschreiber': 2,
    'Strumpffabrikant': 2,
    'Landamman': 1,
    'Vicepräsident': 1,
    'Hofagent': 2,
    'Oberappellations-Procurator': 2,
    'Schreiber': 3,
    'Kantonsrath': 1,
    'Regierungs-Präsident': 1,
    'Post-Director': 1,
    'Kanzleisecretair': 2,
    'Fechtmeister': 3,
    'Handschuhmacher': 3,
    'Witwe d. Kaufmanns B.': 2,
    'Conferenzrath': 1,
    'Pachter': 3
}
