"""Small per-school lookups used by the register cleaners."""

# Erlangen field abbreviations -> standard labels.
FIELD_MAPPING_ERLANGEN = {
    "Theol u. Phil": "Theol; Philol",
    "Theologie und Philosophie": "Theol; Phil",
    "Phys. u. Math.": "Physik; Math",
    "Forst. u. Cam.": "Forstw; Kam",
    "Zoologie": "Zoologie",
    "Rechte u Cam.": "Rechte; Kam",
    "Phil. u. Philos.": "Phil; Philol",
    "Kriegswiss.": "Kriegsw",
    "Forstwissenschaft.": "Forstw",
    "Forstwißensch": "Forstw",
    "Aesthetik": "Aesth",
    "Cam. u. Math.": "Kam; Math",
    "Theol.": "Theol",
    "Schulfach": "Schul",
    "Histor.": "Geschichte",
    "Rechte u. Phil.": "Rechte; Philol",
    "Theolog'e": "Theol",
    "Cam. u. Oek.": "Kam; Econ",
    "Phil. u. Med.": "Philol; Med",
    "Theol. u. Nat.": "Theol; Naturw",
    "Chem. u. Phar.": "Chem; Pharm",
    "Cameral'a": "Kam",
    "Naturgeschichte": "Naturges",
    "Rechte u. Th.": "Rechte; Theol",
    "Chem. u. Phil.": "Chem; Philol",
    "Baukunde": "Eng",
    "Theol u Phil": "Theol; Phil",
    "Pädagogik": "Educ",
    "Jura": "Jura",
    "Forst. u. Cam": "Forstw; Kam",
    "Math. u. Phys.": "Physik; Math",
    "Landwirtschaft": "Landw",
    "Naturwissenschaften": "Naturw",
    "Naturwiss.": "Naturw",
    "Theol. u.": "Theol",
    "Phys. u. Chem.": "Physik; Chem",
    "Cam. u. Forst": "Forstw; Kam",
    "Oeconomie": "Econ",
    "Architekt.": "Arch",
    "Theol. u. Phil": "Theol; Phil",
    "Diplom.": None,
    "Rechten u. Cam.": "Rechte; Kam",
    "Theol. u Phil.": "Theol; Phil",
    "Physik": "Physik",
    "Architect.": "Arch",
    "Math. u. Phil.": "Math; Phil",
    "milit.": "Kriegsw",
    "Sprachen": "Philol",
    "Theol. u. Math.": "Theol; Math",
    "Naturwissensch.": "Naturw",
    "Phil. u. Math.": "Phil; Math",
    "Medizin": "Med",
    "Med. u. Chir.": "Med; Chir",
    "Chemie": "Chem",
    "Phil. u. Theol.": "Phil; Theol",
    "Bergbaukunde": "Eng",
    "Forstwissenschaft": "Forstw",
    "Pharmazie": "Pharm",
    "Forstwissensch.": "Forstw",
    "Mathematik": "Math",
    "Philologie": "Philo",
    "Rechte u. Cam.": "Rechte; Kam",
    "Philosophie": "Phil",
    "Pharmacie": "Pharm",
    "Cameralia": "Kam",
    "Theol. u. Phil.": "Theol; Phil",
    "Chirurgie": "Chir",
    "Medicin": "Med",
    "Rechte": "Rechte",
    "Theologie": "Theol",
}

# Göttingen 1837 volume: the first entry of each matriculation year, identified
# by name and scan page. Entries without a parseable date take the year of the
# most recent anchor at or above them.
GOETTINGEN_YEAR_ANCHORS = [
    {"last_name": "Meyer", "first_names": "Georg Otto Alexander", "source_page": 9, "year_helper": 1837},
    {"last_name": "Brandt", "first_names": "Johann Friedrich", "source_page": 16, "year_helper": 1838},
    {"last_name": "Hachfeld", "first_names": "Georg Wilhelm", "source_page": 25, "year_helper": 1839},
    {"last_name": "Meyer", "first_names": "Georg Friedrich Wilhelm", "source_page": 36, "year_helper": 1840},
    {"last_name": "Kreuster", "first_names": "Wolrad", "source_page": 48, "year_helper": 1841},
    {"last_name": "Predeck", "first_names": "Bernhard Heinr.", "source_page": 61, "year_helper": 1842},
    {"last_name": "Caesar", "first_names": "Heinrich", "source_page": 72, "year_helper": 1843},
    {"last_name": "Weber", "first_names": "Otto Friedrich", "source_page": 84, "year_helper": 1844},
    {"last_name": "Degenhardt", "first_names": "Wilhelm", "source_page": 94, "year_helper": 1845},
    {"last_name": "Arning", "first_names": "Christian Ludwig", "source_page": 104, "year_helper": 1846},
    {"last_name": "von Holle", "first_names": "Georg", "source_page": 113, "year_helper": 1847},
    {"last_name": "van Delden", "first_names": "Friedrich Theodor", "source_page": 121, "year_helper": 1848},
    {"last_name": "Nissen", "first_names": "Ludwig", "source_page": 132, "year_helper": 1849},
    {"last_name": "Harms", "first_names": "Ernst", "source_page": 145, "year_helper": 1850},
]


# Berlin field abbreviations, punctuation stripped -> standard labels.
FIELD_MAPPING_BERLIN = {
    "Meb": "Med",
    "Ram": "Kam",
    "Rchte": "Rechte",
    "Theo": "Theol",
    "Theof": "Theol",
    "Md": "Med",
    "s": None,
    "kam": "Kam",
    "Thol": "Theol",
    "Cam": "Kam",
    "Mineral": "Mineral",
    "Thevl": "Theol",
    "Matth": "Math",
    "": None,
    "Naturw": "Naturw",
    "Math": "Math",
    "Kam": "Kam",
    "Phil": "Phil",
    "Med": "Med",
    "Theol": "Theol",
    "Rechte": "Rechte",
}


# Bonn field names -> standard labels; several fields are joined with '; '.
FIELD_MAPPING_BONN = {
    "Jura": "Jura",
    "kath. Theologie": "Kath Theol",
    "Medicin": "Med",
    "ev. Theologie": "Ev Theol",
    "Philologie": "Philol",
    "Philosophie": "Phil",
    "Medizin": "Med",
    "Jura u. Cameral.": "Jura; Kam",
    "kath. Theol.": "Kath Theol",
    "k. Th.": "Kath Theol",
    "kathol. Theologie": "Kath Theol",
    "Jura u. Cameral": "Jura; Kam",
    "Cameral.": "Kam",
    "Cameral": "Kam",
    "ev. Th.": "Ev Theol",
    "": None,
    "ev. Theol.": "Ev Theol",
    "Philol.": "Philol",
    "Mathematik": "Math",
    "Chirurgie": "Chir",
    "Philos.": "Phil",
    "Medezin": "Med",
    "k. Theologie": "Kath Theol",
    "evang. Theol.": "Ev Theol",
    "k. Theol. u. Phil.": "Kath Theol; Phil",
    "Mineralogie": "Mineral",
    "Jura u. Cameralia": "Jura; Kam",
    "Pharmacie": "Pharm",
    "Bergkunde": "Berge",
    "Cameralia": "Kam",
    "ev. Theol. u. Philol.": "Ev Theol; Philol",
    "k. Theol.": "Kath Theol",
    "Math.": "Math",
    "Naturwissenschaft": "Naturw",
    "Pharm.": "Pharm",
    "Mathem.": "Math",
    "Jura u. Cammeral": "Jura; Kam",
    "k. Th. u. Philol.": "Kath Theol; Philol",
    "Jura und Cameral.": "Jura; Kam",
    "Bergwissenschaft": "Berge",
    "Stud. iuris.": "Jura",
    "katholische Theologie": "Kath Theol",
    "ev. Th. u. Philol.": "Ev Theol; Philol",
    "Med.": "Med",
    "k. Theol. u. Philol.": "Kath Theol; Philol",
    "kath. Theol. u. Philol.": "Kath Theol; Philol",
    "Jura und Cameral": "Jura; Kam",
    "k. Theol., Philol.": "Kath Theol; Philol",
    "Chemie": "Chem",
    "ev Theologie": "Ev Theol",
    "ev. Theol. u. Phil.": "Ev Theol; Phil",
    "Oeconomie": "Econ",
    "Pharmac.": "Pharm",
    "k. Theol. u. Jura": "Kath Theol; Jura",
    "kath Theologie": "Kath Theol",
    "Philologie und kath. Theologie": "Kath Theol; Philol",
    "kathol Theologie": "Kath Theol",
    "Mineral.": "Mineral",
    "Cammeral": "Kam",
    "Pharmaceut": "Pharm",
    "Landwirthschaft": "Landw",
    "Cameral u. Jura": "Jura; Kam",
    "kath. Theolog. u. Philol.": "Kath Theol; Philol",
    "Jura u. Philos.": "Jura; Phil",
    "Oekonomie": "Econ",
    "kath. Theol. u. Philolog.": "Kath Theol; Philol",
    "Jura u. Philosophie": "Jura; Phil",
    "Philol. u. k. Th.": "Kath Theol; Philol",
    "Chirur.": "Chir",
    "Ju": "Jura",
    "Math. u. Naturw.": "Math; Naturw",
    "k. Th. u. Phil.": "Kath Theol; Phil",
    "Phil. u. Mathem.": "Phil; Math",
    "Jura u. Camer.": "Jura; Kam",
    "Chir.": "Chir",
    "Stud. jur.": "Jura",
    "Philos. u. Mathem.": "Phil; Math",
    "Math. u. Physik": "Math; Physik",
    "ev. Th. u. Phil.": "Ev Theol; Phil",
    "ev.": "Ev Theol",
    "Chirurg.": "Chir",
    "Jura Cameral": "Jura; Kam",
    "kath. Theol. u. Philos.": "Kath Theol; Phil",
    "ev. Theologie u. Philol.": "Ev Theol; Philol",
    "Cam. u. Naturw.": "Kam; Naturw",
    "Naturwissensch.": "Naturw",
    "f. Th.": "Ev Theol",
    "evangel. Theologie": "Ev Theol",
    "kath. Theologie u. Philologie": "Kath Theol; Philol",
    "Mathem. u. Physik": "Math; Physik",
    "k. Th. u. Philos.": "Kath Theol; Phil",
    "kath. Theol. Philol.": "Kath Theol; Philol",
    "f. Theol. u. Phil.": "Ev Theol; Phil",
    "k. Theol. u. Philos.": "Kath Theol; Phil",
    "k. Theol. u. Math.": "Kath Theol; Math",
    "kath Theol.": "Kath Theol",
    "Forstwissenschaft": "Forstw",
    "f. Th. u. Philol.": "Ev Theol; Philol",
    "ev. Theol. Philol.": "Ev Theol; Philol",
    "Camer. u. Naturw.": "Kam; Naturw",
    "Medizin u Chirurgie": "Med; Chir",
    "Jura, kath. Theol.": "Jura; Kath Theol",
    "Deconomie": "Econ",
    "kath. Th.ol.": "Kath Theol",
    "k. Th. u. Jura": "Kath Theol; Jura",
    "kth. Theol. u. Philol.": "Kath Theol; Philol",
    "Mathematik u. Philol.": "Math; Phil",
    "Jur. u. Cameral": "Jura; Kam",
    "Philol. u. kath. Theol.": "Kath Theol; Philol",
    "Geschichte": "Geschichte",
    "ev. Theol. Phil.": "Ev Theol; Phil",
    "ev. Theol. u. Philos.": "Ev Theol; Phil",
    "Philos. u. Math.": "Phil; Math",
    "Phil. u. Math.": "Phil; Math",
    "Stud. Cameral.": "Kam",
    "kath. Theol., Phil.": "Kath Theol; Phil",
    "e. Th. u. Philol.": "Ev Theol; Philol",
    "Philos. u. Medicin": "Phil; Med",
    "Mathematik u. Physik": "Math; Physik",
    "Philol. u. ev. Th.": "Ev Theol; Phil",
    "kath. Theol. u. Jura": "Kath Theol; Jura",
    "Mathematik u. Naturw.": "Math; Naturw",
    "kth. Theologie": "Kath Theol",
    "Mathem. u. Phil.": "Math; Phil",
    "Jura u. Cam.": "Jura; Kam",
    "Ph": "Phil",
    "Math. u. Philol.": "Math; Philol",
    "Me": "None",
    "Philos. u. Philol.": "Phil; Philol",
    "ev. Theol, Phil.": "Ev Theol; Phil",
    "ev. Theol., Philol.": "Ev Theol; Philol",
    "Philol. u. Philos.": "Phil; Philol",
    "oriental. Literatur": "Lit",
    "ev. Theol. u. Phil": "Ev Theol; Phil",
    "kath. Th. u. Phil.": "Kath Theol; Phil",
    "evang. Theologie": "Ev Theol",
    "kth. Theol. u. Medicin": "Kath Theol; Med",
    "kath. Philosophie": "Kath Theol",
    "(Kath. Theologie (und Philologie": "Kath Theol; Philol",
    "Jurau. Naturwiss.": "Jura; Naturw",
    "kathol. Teologie": "Kath Theol",
    "Kath. Theol. u. philolog": "Kath Theol; Philol",
    "Philol. u. Pharm.": "Philol; Pharm",
    "kathol. Theolog. u Hist.": "Kath Theol; Geschichte",
    "kat. Theologie": "Kath Theol",
    "k. theol., Philol.": "Kath Theol; Philol",
    "Philos. u. Mediz.": "Phil; Med",
    "Mathem. u. Philol.": "Math; Philol",
    "Stud. philos.": "Phil",
    "orient. Philologie": "Philol",
    "Mathem. u. Philologie": "Math; Philol",
    "oriental. Philosophie": "Phil",
    "Mathematik und Physik": "Math; Physik",
    "lathol. Theologie": "Kath Theol",
    "Jura u. Geschichte": "Jura; Geschichte",
    "Jura u. Staatsw": "Jura; Staatsw",
    "kath. Theologie (und Philologie)": "Kath Theol",
    "Philos. Mathem.": "Phil; Math",
    "kath. Theol. u. Philosophie": "Kath Theol; Phil",
    "Philol. u. ev. Theol.": "Ev Theol; Philol",
    "k. Theo. u. Philol.": "Kath Theol; Philol",
    "Jura u. Philosoph.": "Jura; Phil",
    "Mathem. u. Hist.": "Math; Geschichte",
    "Mathematik und Naturwissenschaft": "Math; Naturw",
    "Philos. u. Naturw.": "Phil; Naturw",
    "Stud. cameral.": "Kam",
    "Philos. u. Jura": "Jura; Phil",
    "Philos. u. Historie": "Philol; Geschichte",
    "Med. u. Chir.": "Med; Chir",
    "Jura und (Philologie)": "Jura; Philol",
    "Dr. Medicin": "Med",
    "Dr. Philologie": "Philol",
    "orient. Litteratur": "Lit",
    "Philos. u. Mathematik": "Phil; Math",
    "evang. Theol. u. Philologie": "Ev Theol; Philol",
    "Orientalia": "Lit",
    "Jur. u. Staatsw.": "Jura; Staatsw",
    "Stud. iuris et cameral.": "Jura; Kam",
    "Mathematit": "Math",
    "Chirurg": "Chir",
    "Philosoph": "Phil",
    "f. Th. u. Philos.": "Ev Theol; Phil",
    "kath. Theologie und Philosophie": "Kath Theol; Phil",
    "(kath. Theol. und Philologie": "Kath Theol; Philol",
    "Philos. u. Cam.": "Kam; Phil",
    "Mathematif": "Math",
    "Forstfach": "Forstw",
    "Jura u. Cammeral.": "Jura; Kam",
    "Medecin": "Med",
    "Philof.": "Phil",
}
