"""Small per-school lookups used by the register cleaners."""

# Erlangen field abbreviations -> standard labels.
FIELD_MAPPING_ERLANGEN = {
    "Theol u. Phil": "Theol; Philol",
    "Theologie und Philosophie": "Theol; Phil",
    "Phys. u. Math.": "Physik; Math",
    "Forst. u. Cam.": "Forstw; Kam",
    "Zoologie": "Zoologie",
    "Rechte u Cam.": "Rechte; Kam",
    "Phil. u. Philos.": "Phil; Philol",
    "Kriegswiss.": "Kriegsw",
    "Forstwissenschaft.": "Forstw",
    "Forstwißensch": "Forstw",
    "Aesthetik": "Aesth",
    "Cam. u. Math.": "Kam; Math",
    "Theol.": "Theol",
    "Schulfach": "Schul",
    "Histor.": "Geschichte",
    "Rechte u. Phil.": "Rechte; Philol",
    "Theolog'e": "Theol",
    "Cam. u. Oek.": "Kam; Econ",
    "Phil. u. Med.": "Philol; Med",
    "Theol. u. Nat.": "Theol; Naturw",
    "Chem. u. Phar.": "Chem; Pharm",
    "Cameral'a": "Kam",
    "Naturgeschichte": "Naturges",
    "Rechte u. Th.": "Rechte; Theol",
    "Chem. u. Phil.": "Chem; Philol",
    "Baukunde": "Eng",
    "Theol u Phil": "Theol; Phil",
    "Pädagogik": "Educ",
    "Jura": "Jura",
    "Forst. u. Cam": "Forstw; Kam",
    "Math. u. Phys.": "Physik; Math",
    "Landwirtschaft": "Landw",
    "Naturwissenschaften": "Naturw",
    "Naturwiss.": "Naturw",
    "Theol. u.": "Theol",
    "Phys. u. Chem.": "Physik; Chem",
    "Cam. u. Forst": "Forstw; Kam",
    "Oeconomie": "Econ",
    "Architekt.": "Arch",
    "Theol. u. Phil": "Theol; Phil",
    "Diplom.": None,
    "Rechten u. Cam.": "Rechte; Kam",
    "Theol. u Phil.": "Theol; Phil",
    "Physik": "Physik",
    "Architect.": "Arch",
    "Math. u. Phil.": "Math; Phil",
    "milit.": "Kriegsw",
    "Sprachen": "Philol",
    "Theol. u. Math.": "Theol; Math",
    "Naturwissensch.": "Naturw",
    "Phil. u. Math.": "Phil; Math",
    "Medizin": "Med",
    "Med. u. Chir.": "Med; Chir",
    "Chemie": "Chem",
    "Phil. u. Theol.": "Phil; Theol",
    "Bergbaukunde": "Eng",
    "Forstwissenschaft": "Forstw",
    "Pharmazie": "Pharm",
    "Forstwissensch.": "Forstw",
    "Mathematik": "Math",
    "Philologie": "Philo",
    "Rechte u. Cam.": "Rechte; Kam",
    "Philosophie": "Phil",
    "Pharmacie": "Pharm",
    "Cameralia": "Kam",
    "Theol. u. Phil.": "Theol; Phil",
    "Chirurgie": "Chir",
    "Medicin": "Med",
    "Rechte": "Rechte",
    "Theologie": "Theol",
}

# Göttingen 1837 volume: the first entry of each matriculation year, identified
# by name and scan page. Entries without a parseable date take the year of the
# most recent anchor at or above them.
GOETTINGEN_YEAR_ANCHORS = [
    {"last_name": "Meyer", "first_names": "Georg Otto Alexander", "source_page": 9, "year_helper": 1837},
    {"last_name": "Brandt", "first_names": "Johann Friedrich", "source_page": 16, "year_helper": 1838},
    {"last_name": "Hachfeld", "first_names": "Georg Wilhelm", "source_page": 25, "year_helper": 1839},
    {"last_name": "Meyer", "first_names": "Georg Friedrich Wilhelm", "source_page": 36, "year_helper": 1840},
    {"last_name": "Kreuster", "first_names": "Wolrad", "source_page": 48, "year_helper": 1841},
    {"last_name": "Predeck", "first_names": "Bernhard Heinr.", "source_page": 61, "year_helper": 1842},
    {"last_name": "Caesar", "first_names": "Heinrich", "source_page": 72, "year_helper": 1843},
    {"last_name": "Weber", "first_names": "Otto Friedrich", "source_page": 84, "year_helper": 1844},
    {"last_name": "Degenhardt", "first_names": "Wilhelm", "source_page": 94, "year_helper": 1845},
    {"last_name": "Arning", "first_names": "Christian Ludwig", "source_page": 104, "year_helper": 1846},
    {"last_name": "von Holle", "first_names": "Georg", "source_page": 113, "year_helper": 1847},
    {"last_name": "van Delden", "first_names": "Friedrich Theodor", "source_page": 121, "year_helper": 1848},
    {"last_name": "Nissen", "first_names": "Ludwig", "source_page": 132, "year_helper": 1849},
    {"last_name": "Harms", "first_names": "Ernst", "source_page": 145, "year_helper": 1850},
]
